{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "numa-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "numa-scheduler.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "numa-scheduler.fullname" . }}
  labels:
    {{- include "numa-scheduler.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "numa-scheduler.fullname" . }}
  labels:
    {{- include "numa-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "numa-scheduler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "numa-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}